package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private Integer branchId;
	private String branchName;
	private String site;

	public Branch() {
	}

	public Branch(String branchName, String site) {
		this.branchName = branchName;
		this.site = site;
	}

	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
