package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

/**
 * Demo generated by hbm2java
 */
public class Demo implements java.io.Serializable {

	private DemoId id;

	public Demo() {
	}

	public Demo(DemoId id) {
		this.id = id;
	}

	public DemoId getId() {
		return this.id;
	}

	public void setId(DemoId id) {
		this.id = id;
	}

}
