package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer deptid;
	private String deptname;
	private Integer deptnum;
	private String deptdesc;
	private Set emps = new HashSet(0);

	public Dept() {
	}

	public Dept(String deptname, Integer deptnum, String deptdesc, Set emps) {
		this.deptname = deptname;
		this.deptnum = deptnum;
		this.deptdesc = deptdesc;
		this.emps = emps;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptnum() {
		return this.deptnum;
	}

	public void setDeptnum(Integer deptnum) {
		this.deptnum = deptnum;
	}

	public String getDeptdesc() {
		return this.deptdesc;
	}

	public void setDeptdesc(String deptdesc) {
		this.deptdesc = deptdesc;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set emps) {
		this.emps = emps;
	}

}
