package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer empid;
	private Dept dept;
	private String empname;
	private String empsex;
	private Integer empage;
	private String empphoto;
	private String empaddress;
	private Date empdate;

	public Emp() {
	}

	public Emp(Dept dept, String empname, String empsex, Integer empage, String empphoto, String empaddress,
			Date empdate) {
		this.dept = dept;
		this.empname = empname;
		this.empsex = empsex;
		this.empage = empage;
		this.empphoto = empphoto;
		this.empaddress = empaddress;
		this.empdate = empdate;
	}

	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public String getEmpsex() {
		return this.empsex;
	}

	public void setEmpsex(String empsex) {
		this.empsex = empsex;
	}

	public Integer getEmpage() {
		return this.empage;
	}

	public void setEmpage(Integer empage) {
		this.empage = empage;
	}

	public String getEmpphoto() {
		return this.empphoto;
	}

	public void setEmpphoto(String empphoto) {
		this.empphoto = empphoto;
	}

	public String getEmpaddress() {
		return this.empaddress;
	}

	public void setEmpaddress(String empaddress) {
		this.empaddress = empaddress;
	}

	public Date getEmpdate() {
		return this.empdate;
	}

	public void setEmpdate(Date empdate) {
		this.empdate = empdate;
	}

}
