package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private Date stoday;

	public Students() {
	}

	public Students(String sname, Date stoday) {
		this.sname = sname;
		this.stoday = stoday;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Date getStoday() {
		return this.stoday;
	}

	public void setStoday(Date stoday) {
		this.stoday = stoday;
	}

}
