package com.web.pojo;
// Generated 2019-12-18 21:11:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer uid;
	private Role role;
	private String uname;
	private String upwd;
	private Date ubirthday;
	private String uphoto;

	public Users() {
	}

	public Users(Role role, String uname, String upwd, Date ubirthday, String uphoto) {
		this.role = role;
		this.uname = uname;
		this.upwd = upwd;
		this.ubirthday = ubirthday;
		this.uphoto = uphoto;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public Date getUbirthday() {
		return this.ubirthday;
	}

	public void setUbirthday(Date ubirthday) {
		this.ubirthday = ubirthday;
	}

	public String getUphoto() {
		return this.uphoto;
	}

	public void setUphoto(String uphoto) {
		this.uphoto = uphoto;
	}

}
